[package]
name = "meibo_manager"
version = "0.1.0"
authors = ["Iori Ogura <barojuu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
